---
channels:
    1:
        active: false
        color: FF0000
    2:
        active: false
    3:
        active: true
        color: 00FF00
    4:
        active: false
    5:
        active: false
    6:
        active: false
    7:
        active: false
    8:
        active: true
        color: 00FF00
    9:
        active: false
    10:
        active: true
        color: 00FF00
        end: 0.05
        max: 0.05
        min: 0.0
        start: 0.0
    11:
        active: false
    12:
        active: false
    18:
        active: true
        color: FF0000
    21:
        active: false
    22:
        active: true
        color: FF0000
        end: 0.05
        max: 0.05
        min: 0.0
        start: 0.0
    28:
        active: true
        color: 0000FF
    29:
        active: true
        color: 0000FF
greyscale: false
version: 2

